// <auto-generated />
using System;
using Estapar.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Estapar.Infraestructure.Migrations
{
    [DbContext(typeof(EstaparContext))]
    partial class EstaparContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Estapar.Domain.Entities.GarageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("ParkId");

                    b.ToTable("Garages", (string)null);
                });

            modelBuilder.Entity("Estapar.Domain.Entities.LaneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LaneType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Name");

                    b.HasIndex("ParkId");

                    b.HasIndex("Status");

                    b.ToTable("Lanes", (string)null);
                });

            modelBuilder.Entity("Estapar.Domain.Entities.ParkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Name");

                    b.ToTable("Parks", (string)null);
                });

            modelBuilder.Entity("Estapar.Domain.Entities.ParkedVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntryTrafficId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntryTrafficId")
                        .IsUnique();

                    b.HasIndex("GarageId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("ParkedVehicles", (string)null);
                });

            modelBuilder.Entity("Estapar.Domain.Entities.PriceTableEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GracePeriodMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("ParkId")
                        .IsUnique();

                    b.ToTable("PriceTables", (string)null);
                });

            modelBuilder.Entity("Estapar.Domain.Entities.TrafficEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Error")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("LaneId")
                        .HasColumnType("uuid");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Date");

                    b.HasIndex("LaneId");

                    b.HasIndex("LicensePlate");

                    b.ToTable("Traffics", (string)null);
                });

            modelBuilder.Entity("Estapar.Domain.Entities.TransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntryTrafficId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExitTrafficId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StayDuration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("EntryTrafficId")
                        .IsUnique();

                    b.HasIndex("ExitTrafficId")
                        .IsUnique();

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Estapar.Domain.Entities.GarageEntity", b =>
                {
                    b.HasOne("Estapar.Domain.Entities.ParkEntity", "Park")
                        .WithMany("Garages")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("Estapar.Domain.Entities.LaneEntity", b =>
                {
                    b.HasOne("Estapar.Domain.Entities.ParkEntity", "Park")
                        .WithMany("Lanes")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("Estapar.Domain.Entities.ParkedVehicleEntity", b =>
                {
                    b.HasOne("Estapar.Domain.Entities.TrafficEntity", "EntryTraffic")
                        .WithMany()
                        .HasForeignKey("EntryTrafficId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estapar.Domain.Entities.GarageEntity", "Garage")
                        .WithMany("ParkedVehicles")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntryTraffic");

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("Estapar.Domain.Entities.PriceTableEntity", b =>
                {
                    b.HasOne("Estapar.Domain.Entities.ParkEntity", "Park")
                        .WithOne("PriceTable")
                        .HasForeignKey("Estapar.Domain.Entities.PriceTableEntity", "ParkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("Estapar.Domain.Entities.TrafficEntity", b =>
                {
                    b.HasOne("Estapar.Domain.Entities.LaneEntity", "Lane")
                        .WithMany()
                        .HasForeignKey("LaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lane");
                });

            modelBuilder.Entity("Estapar.Domain.Entities.TransactionEntity", b =>
                {
                    b.HasOne("Estapar.Domain.Entities.TrafficEntity", "EntryTraffic")
                        .WithMany()
                        .HasForeignKey("EntryTrafficId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estapar.Domain.Entities.TrafficEntity", "ExitTraffic")
                        .WithMany()
                        .HasForeignKey("ExitTrafficId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntryTraffic");

                    b.Navigation("ExitTraffic");
                });

            modelBuilder.Entity("Estapar.Domain.Entities.GarageEntity", b =>
                {
                    b.Navigation("ParkedVehicles");
                });

            modelBuilder.Entity("Estapar.Domain.Entities.ParkEntity", b =>
                {
                    b.Navigation("Garages");

                    b.Navigation("Lanes");

                    b.Navigation("PriceTable");
                });
#pragma warning restore 612, 618
        }
    }
}
